import { WaitlistEntry } from "./waitlist";

export const mockWaitlistData: WaitlistEntry[] = [
  {
    id: "wl-1",
    firstName: "Anna",
    lastName: "Schmidt",
    email: "anna.schmidt@example.com",
    mobile: "+49 151 12345678",
    age: 32,
    reason: "I am interested in your yoga classes and would like to join as soon as possible.",
    availability: "monday morning,wednesday afternoon,friday morning",
    message: "I have some experience with yoga but would consider myself a beginner.",
    contactPerson: "Feli",
    status: "contacted",
    notes: "Called on 15.03, will follow up next week",
    createdAt: "2023-03-10T14:30:00Z",
  },
  {
    id: "wl-2",
    firstName: "Thomas",
    lastName: "Müller",
    email: "thomas.mueller@example.com",
    mobile: "+49 170 9876543",
    age: 45,
    reason: "Looking for physiotherapy sessions for back pain issues.",
    availability: "tuesday morning,thursday morning",
    message: "I have chronic back pain and my doctor recommended your center.",
    contactPerson: "Olga",
    status: "accepted",
    notes: "First appointment scheduled for 25.04",
    createdAt: "2023-03-15T09:15:00Z",
  },
  {
    id: "wl-3",
    firstName: "Sophie",
    lastName: "Weber",
    email: "sophie.weber@example.com",
    mobile: "+49 176 5432198",
    age: 28,
    reason: "Interested in meditation classes to help with stress management.",
    availability: "monday afternoon,wednesday afternoon,friday afternoon",
    message: "I work in a high-stress environment and need to learn relaxation techniques.",
    contactPerson: null,
    status: "waiting",
    notes: "",
    createdAt: "2023-03-18T16:45:00Z",
  },
  {
    id: "wl-4",
    firstName: "Michael",
    lastName: "Fischer",
    email: "michael.fischer@example.com",
    mobile: "+49 177 8765432",
    age: 52,
    reason: "Need rehabilitation after knee surgery.",
    availability: "monday morning,tuesday morning,wednesday morning,thursday morning,friday morning",
    message: "I had knee replacement surgery 6 weeks ago and need professional rehabilitation.",
    contactPerson: "Svetlana",
    status: "declined",
    notes: "Patient found another facility closer to home",
    createdAt: "2023-03-05T11:20:00Z",
  },
  {
    id: "wl-5",
    firstName: "Julia",
    lastName: "Becker",
    email: "julia.becker@example.com",
    mobile: "+49 152 3456789",
    age: 35,
    reason: "Looking for prenatal yoga classes.",
    availability: "saturday morning,sunday morning",
    message: "I am in my second trimester and would like to join prenatal yoga classes.",
    contactPerson: "Feli",
    status: "waiting",
    notes: "Left voicemail on 20.03",
    createdAt: "2023-03-20T13:10:00Z",
  },
  {
    id: "wl-6",
    firstName: "Markus",
    lastName: "Hoffmann",
    email: "markus.hoffmann@example.com",
    mobile: "+49 179 2345678",
    age: 41,
    reason: "Interested in personal training sessions for weight loss.",
    availability: "tuesday afternoon,thursday afternoon",
    message: "I need to lose weight for health reasons and would like personalized guidance.",
    contactPerson: "Olga",
    status: "contacted",
    notes: "Scheduled initial consultation for 28.03",
    createdAt: "2023-03-22T10:05:00Z",
  },
]
