import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import TanStackQuery from "@/provider/tanstack-query";
import { ThemeProvider } from "@/provider/theme-provider";
import AiAssistant from "@/components/ai-assistant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackQuery>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <AiAssistant>{children}</AiAssistant>
          </ThemeProvider>
        </TanStackQuery>
      </body>
    </html>
  );
}
